# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44548bac7a3bbf05a13d7456f1a93e3d36400e4b4cf119d55558fc53ef3b4516ef95d5dbbfc82e1de9540ad0a5b812820cfc6ae4574a920706d5385e35721895

test:
  secret_key_base: 3e79fcc2f115a0c17feb72c24d31a0cdce703238d167ac21de654cc320a80e310368fb9273c41d36870402bc3201da73bbc80c10acbdbbead0e13bd1723cbdd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
